### ISSUE TITLE
Missing some runbook contents

### ISSUE THREAD

**Issue by wangyanzhao** [prometheus-operator/kube-prometheus#1535] opened 2021-12-03 12:19 UTC
**What happened?**

Some runbook_url annotations in PromethuesRule is 404，such as https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-prometheusRule.yaml#L258 .

https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclientcertificateexpiration

**Did you expect to see some different?**

All runbook_url should not be 404.

**Comment by paulfantom** [comment] 2021-12-03 13:17
Feel free to contribute those runbooks in https://github.com/prometheus-operator/runbooks, we cannot do this alone. The 404 page even says so :)

> We would like to have runbooks for all alerts shipped with kube-prometheus, but we sadly don't have time to write them all.

I am closing this as this is not a bug and we expect community to chime in and write runbooks.

**Closed by paulfantom** 2021-12-03 13:17 UTC
Labels: kind/bug
