### ISSUE TITLE
Master failing on AKS RBAC cluster v1.18.8 Adapter and Operator CrashLoopBackOff 

### ISSUE THREAD

**Issue by ajay1206** [prometheus-operator/kube-prometheus#756] opened 2020-11-05 12:55 UTC
All the pre requisite CRD's were deployed. And webhook flags verified on the kube server too.

Operator error : "Unhandled error received. Exiting..." err="communicating with server failed: an error on the server (\"\") has prevented the request from succeeding"

Adapter error : unable to install resource metrics API: unable to construct dynamic discovery mapper: unable to populate initial set of REST mappings: an error on the server ("") has prevented the request from succeeding

metric-server is running on kube-system fine, able to reach kube-api

**Comment by paulfantom** [comment] 2020-11-05 13:43
Closing as duplicate of #755. Let's move the potential discussion into that thread.

**Closed by paulfantom** 2020-11-05 13:43 UTC
Labels: kind/support
