### ISSUE TITLE
I have a need to monitor applications outside the cluster, how can I configure TLS  through ServiceMonitor

### ISSUE THREAD

**Issue by COCONUTYA1** [prometheus-operator/kube-prometheus#1739] opened 2022-04-25 10:27 UTC
Hello everyone，I have a need to monitor applications outside the cluster, how can I configure TLS and basic auth through ServiceMonitor？

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter1
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  jobLabel: node-exporter
  endpoints:
  - port: port
    interval: 30s
  selector:
    matchLabels:
      app: node-exporter
  namespaceSelector:
    matchNames:
    - monitoring
```

**Comment by PhilipGough** [comment] 2022-04-28 15:35
Right now, I am not sure we have a good way to do this.

This looks like a duplicate of #1358 and there is a similar ask in https://github.com/prometheus-operator/prometheus-operator/issues/4748

@paulfantom were you looking into a solution for this at some stage?

**Closed** 2022-04-29 12:53 UTC
Labels: kind/support
