### ISSUE TITLE
"prometheuses.monitoring.coreos.com" is invalid

### ISSUE THREAD

**Issue by vinzol** [prometheus-operator/kube-prometheus#1533] opened 2021-12-03 03:11 UTC
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

**Comment by paulfantom** [comment] 2021-12-03 09:07
Duplicate of https://github.com/prometheus-operator/kube-prometheus/issues/1511

Please use `kubectl apply --server-side`.

**Closed by paulfantom** 2021-12-03 09:07 UTC
Labels: kind/bug, duplicate

**Comment by freemankevin** [comment] 2023-05-22 02:55
`kubectl apply --server-side -f bundle.yaml `

**Comment by freemankevin** [comment] 2023-05-22 02:56
`kubectl apply --server-side -f bundle.yaml `
