### ISSUE TITLE
jb install fails with 0.7

### ISSUE THREAD

**Issue by herveleclerc** [prometheus-operator/kube-prometheus#1008] opened 2021-03-05 15:34 UTC
**What happened?**

the command `jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus@release-0.7`

generate a panic on rename

**How to reproduce it (as minimally and precisely as possible)**:

```
jb init
jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus@release-0.7
```

error : 
```
GET https://github.com/coreos/kube-prometheus/archive/4dbc23c923a8c1978e7daea6eb301623d75a9be1.tar.gz 200
GET https://github.com/kubernetes/kube-state-metrics/archive/e72315512a38653b19dcfe4429f93eadedc0ea96.tar.gz 200
GET https://github.com/prometheus/prometheus/archive/26d89b4b0776fe4cd5a3656dfa520f119a375273.tar.gz 200
GET https://github.com/prometheus/alertmanager/archive/193ebba04d1e70d971047e983a0b489112610460.tar.gz 200
GET https://github.com/etcd-io/etcd/archive/e8ba375032e8e48d009759dfb285f7812e7bcb8c.tar.gz 200
panic: rename /Users/hleclerc/tmp/jjj/vendor/.tmp/jsonnetpkg-github.com-etcd-io-etcd-contrib-mixin-e8ba375032e8e48d009759dfb285f7812e7bcb8c647930610/contrib/mixin /Users/hleclerc/tmp/jjj/vendor/github.com/etcd-io/etcd/contrib/mixin: no such file or directory

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/pkg.(*GitPackage).Install(0xc0000b20f0, 0x14ca7a0, 0xc0000b6030, 0xc0001e4e70, 0x25, 0xc0000b85e0, 0x1e, 0xc00044de30, 0x28, 0x0, ...)
	/Users/hleclerc/go/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/git.go:220 +0x1d56
github.com/jsonnet-bundler/jsonnet-bundler/pkg.download(0xc00051c410, 0x0, 0xc00044de30, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000b85e0, ...)
	/Users/hleclerc/go/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go:289 +0x1aa
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0xc0004efe90, 0xc0000b85e0, 0x1e, 0xc00009bf80, 0x0, 0x0, 0x0)
	/Users/hleclerc/go/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go:233 +0x6c8
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0xc00009bf20, 0xc0000b85e0, 0x1e, 0xc00009bf80, 0x1e, 0x0, 0x1)
	/Users/hleclerc/go/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go:259 +0xef6
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure(0xc00009bf20, 0x1, 0xc0000b85e0, 0x1e, 0xc00009bf80, 0x0, 0x0, 0x0)
	/Users/hleclerc/go/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go:55 +0x67
main.installCommand(0xc00001a044, 0x17, 0x14352ca, 0x6, 0xc000098fc0, 0x1, 0x1, 0x0, 0x0)
	/Users/hleclerc/go/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/install.go:75 +0x74c
main.Main(0xc00008e058)
	/Users/hleclerc/go/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:82 +0xb07
main.main()
	/Users/hleclerc/go/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:37 +0x22
	
```

**Comment by ndegory** [comment] 2021-03-05 16:02
I experience the same since #980 has been merged. Commit c1130442d68bf4bfbd1544711b67c98a28f2a327 works for me.

**Comment by starcraft66** [comment] 2021-03-05 16:36
I can reproduce the same issue.

**Comment by herveleclerc** [comment] 2021-03-05 17:45
I think that the etcd-mixin is not at the right place in the archive. it leaves in **Documentation** directory in tar.gz file. A mistake by the maintainer of etcd mixin maybe.

**Comment by paulfantom** [comment] 2021-03-05 18:13
Etcd changed repository layout and now mixin is located in `contrib/mixin`. However, the issue is we are using that layout, but pinning to commit with an older one. https://github.com/prometheus-operator/kube-prometheus/pull/1009 should fix that.

**Comment by paulfantom** [comment] 2021-03-26 16:12
Closing as #1009 was merged. Please reopen if this is still causing problems.

**Closed by paulfantom** 2021-03-26 16:12 UTC
Labels: kind/bug
