### ISSUE TITLE
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@main not working

### ISSUE THREAD

**Issue by jibinrajck** [prometheus-operator/kube-prometheus#2227] opened 2023-09-29 07:07 UTC
The steps mentioned here not working. - https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizing.md#installing 

When you run jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@main, it errors out with below error message. 

`jchammal@jchammal-desktop:~/apps/monitoring/v1/upstream-jsonnet$ jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@main
GET https://github.com/prometheus-operator/kube-prometheus/archive/98df18a75e0d2960720a5222592005646a68488b.tar.gz 200
GET https://github.com/coreos/kube-prometheus/archive/53f18a42769ea1d4bce833962a908f84069ef495.tar.gz 200
GET https://github.com/kubernetes/kube-state-metrics/archive/b91dd311397047f15aae4f6dacba0708f24cf446.tar.gz 200
GET https://github.com/kubernetes/kube-state-metrics/archive/b91dd311397047f15aae4f6dacba0708f24cf446.tar.gz 200
GET https://github.com/pyrra-dev/pyrra/archive/e29c5d3d59311b19f9e42693c2214d406c24c67c.tar.gz 200
panic: rename /home/jchammal/apps/monitoring/v1/upstream-jsonnet/vendor/.tmp/9a7929ebbffc63d4be4e160c61f673031661834597/config/crd/bases /home/jchammal/apps/monitoring/v1/upstream-jsonnet/vendor/github.com/pyrra-dev/pyrra/config/crd/bases: no such file or directory

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/pkg.(*GitPackage).Install(0xc0004f2068, {0x8764f8, 0xc0000220a0}, {0xc000020f30, 0x2b}, {0xc000026480, 0x54}, {0xc000023470, 0x4})
        /home/jchammal/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.5.1/pkg/git.go:228 +0x1a4b
github.com/jsonnet-bundler/jsonnet-bundler/pkg.download({{0xc000078ff0, 0x0}, {0xc000023470, 0x4}, {0x0, 0x0}, 0x0, {0x0, 0x0}}, {0xc000026480, ...}, ...)
        /home/jchammal/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.5.1/pkg/packages.go:309 +0x3b1
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0xc0004fc320?, {0xc000026480, 0x54}, {0xc0004fc3c0, 0x9b}, 0x0?)
        /home/jchammal/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.5.1/pkg/packages.go:234 +0x61d
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0x53?, {0xc000026480, 0x54}, {0x0, 0x0}, 0x54?)
        /home/jchammal/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.5.1/pkg/packages.go:265 +0xcea
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure({0xc000172300?, 0x10?}, {0xc000026480, 0x54}, 0x0?)
        /home/jchammal/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.5.1/pkg/packages.go:55 +0x54
main.installCommand({0xc000026004?, 0x7f369b?}, {0x7df7da, 0x6}, {0xc00005afe0, 0x1, 0xc000046601?}, 0x0, {0x0, 0x0})
        /home/jchammal/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.5.1/cmd/jb/install.go:85 +0x8bf
main.Main()
        /home/jchammal/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.5.1/cmd/jb/main.go:87 +0xd4a
main.main()
        /home/jchammal/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.5.1/cmd/jb/main.go:39 +0x19`

**Comment by metalmatze** [comment] 2023-09-30 11:41
Thanks for opening this issue. 
It's a duplicate of https://github.com/prometheus-operator/kube-prometheus/issues/2224

**Closed by metalmatze** 2023-09-30 11:41 UTC
Labels: kind/bug

**Comment by jibinrajck** [comment] 2023-10-01 05:48
Thanks for the fix.
